version: '3.4'

services:
  productmanagment.api:
    image: ${DOCKER_REGISTRY-}productmanagmentapi
    build:
      context: .
      dockerfile: ProductManagment.Api/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Legoswtcs1!"
        ACCEPT_EULA: "Y"