version: '3.4'

services:
  productmanagment.api:
    image: ${DOCKER_REGISTRY-}productmanagmentapi
    container_name: web
    build:
      context: .
      dockerfile: ProductManagment.Api/Dockerfile
    depends_on:
      - db
      - migrator
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Legoswtcs1!"
        ACCEPT_EULA: "Y"
  migrator:
    image: ${DOCKER_REGISTRY-}productmanagmentmigrator
    container_name: migrator
    build:
      context: .
      dockerfile: ProductManagment.Migrator/Dockerfile
    depends_on:
      - db
    environment:
        DbConnection: "Server=db;Database=ProductManagment;User=sa;Password=Legoswtcs1!;"